language: node_js
node_js: lts/*
services:
- mongodb
before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.9.3
deploy:
  provider: heroku
  api_key:
    secure: Q4t4cSnGrysFqiyCJj7E2hx1JDh0+8GSerCGR5PYzj+7zfCS16AyiSccVB7sSFrQxYwmRFMBWPKSruqKm4/rTLXQ/p6wqsJYXYkle6SWOlhENQPflSfYBV3V1MNhQGM0fXqNfvPCJjyRdvqD05on9Q+MhuQA9N0VYwGDSS0+8L5hTs7jrRKN+thomhq5sipSrwSpWG0Bgt8IMwBZO0x0BzuO57Ix5DR5SUl+iXGZS1/uj5yDyWlLxboEH2p18EOUttntESwLtQPRigrNvxK+5Q41j4VVHktOtEyKU3TTJfugVg1NtpDTZVhkIDB1Xjz4+q7FaT6JNUeTbVix4kuSQ/8chjw4pb3kyOmAVCoUhtjmLQuzL4NrvPWyHwHlLzScGpxuHCckyd4QTuagRWK2KoHcrrRAhZJAH8kYZ75Tq7bm+clkjubtaeGNtdSK/YavQcemVgzSRDrN6y7Qml+tIx9wtQJZsm+4XRKuaLTqSqEmsy73CDiOTYWL4lPKdIjV1zwW+vkTnt4x36CFihWCMpuYsDoiAPf8SOEG+kCqycMhH4Sc+YHTeO6TOuX0wH2k1R9bl4FVQPsJWk9ryg3OgmEgS559xmkRDBab8dbRjKQ7Ze8x4Sr34MkfWwrduAobmxgv4TLiYMLSan4BMsZjVdGtN1zagTExGPTacjGEYVA=
  app: tasks-and-treasures-api
  on:
    repo: dermio/tasks-and-treasures-API
