language: node_js
node_js: lts/*
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: UquvKilprsKHqEb0jER4lVy03KlrtYRrgpR1P+IMilxGL55ARr6Uwn38CM9sw79g0iDnQOPrEHXwuUtxQjYVtgIjvNB8kHraEvRU5p41c2ng6L9RuY/yQxqKAERNbgLauemfTg9oGhUjK0Q3sINZWTnBbxP3DnaLQT90stvx8wX+fK9riZtM8LZwFxaXc7e005AgFqnH9dV3hKT4xrKqLvcjQDg9b8S16N92iM1QxAvjMYc4P7hDTo2WJIYsK5azFs04FmGd0tYzJAXZkhcnQS+Qrf3sE7LDAEQiQOctLx2b83ge2a3lvMc50S1RupG04qtAKYUK5XjAT7Lp//ZxiGt9xplUPMoukpxoFKhJ+HsUMFzStpDOxMQ9ByvYQSYYeFRrGY1ArEPWI8iDcG/DfK7Nr+PVpF3E4vMtoUV9lgRTge5r7hGZgu/7Uz0ZEhLVigWN9wgHKzYnfeY1rxwaCATFbZro0X4GRHaVDPzxZdBElVSc9IgQmuItZKqUu/Z2+4u5hoE/ny64Pl9WuZqNRq3Q1Lq8WuHSN6tRy6wjUeVqIggBA/I/VIw97Si/F5fZQLemw4lTGi4MnN430kjSQC2KfTwC10gzESmvK8cjmJi6/4EpYiCYx0blCNaNUY/v+z0XhsaG0u5dKje6W2EzVnkFHGdDX2B5C6E6+pTduts=
  app: tasks-and-treasures-api
  on:
    repo: dermio/tasks-and-treasures-API
