language: node_js
node_js: lts/*
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: Z9EMThAFpc5dzHDQGB8ZHDAsJR26Ct6rzYpo4WwyoUUuEdupqfejzAPdj2tzUjA9kz04ubglS0nE9D9rnvMDp6fwt/7i5ZMveqWybpxv2bgQnES8rhmzA8daWLZF7eSzt1WpRJARkjYKJ5dpm8Ig4loqOYjeujbLotsqM+6zOhh+1zZFuqwd7bhkEFK0o5C+sl9gKqeFG00CeZz+Pw9C5n39PRItIwNFxg6ZpZ6RR/PNUu8SuyTT00ZUq1VTenprqOkZV1ejFfthq76ZyevkMnEp8edOFjSWl+moXh1VtapXcKkP1F2qAtDhlHeEiyAGHA4iFLvdy9GIDxXG58mdiCDOHR4avzv9qiPr1C33VkjhlePgeAbZfN/ZbvneNPo9T3HLRvVV7FfdIWO1TFJc2/KOh4I5vSJ2w+9gH1LdBe92MYUYvQHWXhpz3CAEgbol9OuWh9k/5NxZqOJHe8uJsvd2x55rxlQBPXpdmABMGjmXmFE1c1v5SQOdLbO6XBdikUrsplQHeIUcVOoEfQBqJmlHQbGPGUE2w5iVFNooo5FKFFI/WCIsd22oYu4qQzqZRtnjjuYspXdbASW09ZJQU7vt7ZBaTIBMF2YZGj2N7+Gdv7zBc3RaK/yb4N2ZYMPgBcwLRgRzRToWkShyC31BBPARwIj3zPdJqUbYypCBXx8=
  app: tasks-and-treasures-api
  on:
    repo: dermio/tasks-and-treasures-API
